/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface IGovernanceRootPublisherInterface extends Interface {
    getFunction(nameOrSignature: "getProposalCore"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'getProposalCore', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'getProposalCore', data: BytesLike): Result;
  }

  

  export interface IGovernanceRootPublisher extends BaseContract {
    
    connect(runner?: ContractRunner | null): IGovernanceRootPublisher;
    waitForDeployment(): Promise<this>;

    interface: IGovernanceRootPublisherInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getProposalCore: TypedContractMethod<
      [proposalId: BigNumberish, ],
      [[string, string, bigint, bigint, string, string, bigint] & {proposer: string, actionDataHash: string, snapshotBlock: bigint, ER_snapshot: bigint, powerRoot: string, metadata: string, createdAt: bigint }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getProposalCore'): TypedContractMethod<
      [proposalId: BigNumberish, ],
      [[string, string, bigint, bigint, string, string, bigint] & {proposer: string, actionDataHash: string, snapshotBlock: bigint, ER_snapshot: bigint, powerRoot: string, metadata: string, createdAt: bigint }],
      'view'
    >;

    

    filters: {
      
    };
  }