/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GovernanceExecutor } from './GovernanceExecutor.js';
export type { IGovernanceRootPublisher } from './IGovernanceRootPublisher.js';