/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'GovernanceExecutor', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.GovernanceExecutor__factory>
getContractFactory(name: 'IGovernanceRootPublisher', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IGovernanceRootPublisher__factory>
getContractFactory(name: 'GovernanceRootPublisher', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.GovernanceRootPublisher__factory>
getContractFactory(name: 'LiquidStakingVault', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.LiquidStakingVault__factory>
getContractFactory(name: 'WithdrawalNFT', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.WithdrawalNFT__factory>
getContractFactory(name: 'MockERC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockERC20__factory>
getContractFactory(name: 'VoteVerifier', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.VoteVerifier__factory>

  getContractAt(name: 'GovernanceExecutor', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.GovernanceExecutor>
getContractAt(name: 'IGovernanceRootPublisher', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IGovernanceRootPublisher>
getContractAt(name: 'GovernanceRootPublisher', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.GovernanceRootPublisher>
getContractAt(name: 'LiquidStakingVault', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.LiquidStakingVault>
getContractAt(name: 'WithdrawalNFT', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.WithdrawalNFT>
getContractAt(name: 'MockERC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockERC20>
getContractAt(name: 'VoteVerifier', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.VoteVerifier>

  deployContract(name: 'GovernanceExecutor', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.GovernanceExecutor>
deployContract(name: 'IGovernanceRootPublisher', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IGovernanceRootPublisher>
deployContract(name: 'GovernanceRootPublisher', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.GovernanceRootPublisher>
deployContract(name: 'LiquidStakingVault', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LiquidStakingVault>
deployContract(name: 'WithdrawalNFT', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.WithdrawalNFT>
deployContract(name: 'MockERC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC20>
deployContract(name: 'VoteVerifier', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.VoteVerifier>

  deployContract(name: 'GovernanceExecutor', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.GovernanceExecutor>
deployContract(name: 'IGovernanceRootPublisher', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IGovernanceRootPublisher>
deployContract(name: 'GovernanceRootPublisher', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.GovernanceRootPublisher>
deployContract(name: 'LiquidStakingVault', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LiquidStakingVault>
deployContract(name: 'WithdrawalNFT', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.WithdrawalNFT>
deployContract(name: 'MockERC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockERC20>
deployContract(name: 'VoteVerifier', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.VoteVerifier>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  