/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC721 } from './ERC721.js';
export type { ERC721TokenReceiver } from './ERC721TokenReceiver.js';