/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as governanceExecutorSol from './GovernanceExecutor.sol/index.js';
export type { governanceExecutorSol };
export type { GovernanceRootPublisher } from './GovernanceRootPublisher.js';
export type { VoteVerifier } from './VoteVerifier.js';