/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IGovernanceRootPublisher, IGovernanceRootPublisherInterface } from "../../../governance/GovernanceExecutor.sol/IGovernanceRootPublisher.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "proposalId",
        "type": "uint256"
      }
    ],
    "name": "getProposalCore",
    "outputs": [
      {
        "internalType": "address",
        "name": "proposer",
        "type": "address"
      },
      {
        "internalType": "bytes32",
        "name": "actionDataHash",
        "type": "bytes32"
      },
      {
        "internalType": "uint256",
        "name": "snapshotBlock",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "ER_snapshot",
        "type": "uint256"
      },
      {
        "internalType": "bytes32",
        "name": "powerRoot",
        "type": "bytes32"
      },
      {
        "internalType": "string",
        "name": "metadata",
        "type": "string"
      },
      {
        "internalType": "uint256",
        "name": "createdAt",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IGovernanceRootPublisher__factory {
    static readonly abi = _abi;
    static createInterface(): IGovernanceRootPublisherInterface {
      return new Interface(_abi) as IGovernanceRootPublisherInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IGovernanceRootPublisher {
      return new Contract(address, _abi, runner) as unknown as IGovernanceRootPublisher;
    }
  }
  