/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface LiquidStakingVaultInterface extends Interface {
    getFunction(nameOrSignature: "WAD" | "allowance" | "approve" | "asset" | "assetsToShares" | "balanceOf" | "claim" | "decimals" | "deposit" | "distributeRewards" | "exchangeRate" | "governanceExecutor" | "initiateWithdraw" | "lockedAssets" | "name" | "owner" | "renounceOwnership" | "setGovernanceExecutor" | "setUnbondingPeriod" | "sharesToAssets" | "symbol" | "totalSupply" | "transfer" | "transferFrom" | "transferOwnership" | "unbondingPeriod" | "withdrawalNFT"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Approval" | "Claimed" | "Deposited" | "DistributedRewards" | "InitiatedWithdraw" | "OwnershipTransferred" | "Transfer" | "UnbondingPeriodUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'WAD', values?: undefined): string;
encodeFunctionData(functionFragment: 'allowance', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'approve', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'asset', values?: undefined): string;
encodeFunctionData(functionFragment: 'assetsToShares', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'balanceOf', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'claim', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'decimals', values?: undefined): string;
encodeFunctionData(functionFragment: 'deposit', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'distributeRewards', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'exchangeRate', values?: undefined): string;
encodeFunctionData(functionFragment: 'governanceExecutor', values?: undefined): string;
encodeFunctionData(functionFragment: 'initiateWithdraw', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'lockedAssets', values?: undefined): string;
encodeFunctionData(functionFragment: 'name', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setGovernanceExecutor', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setUnbondingPeriod', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'sharesToAssets', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'symbol', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalSupply', values?: undefined): string;
encodeFunctionData(functionFragment: 'transfer', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferFrom', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'unbondingPeriod', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdrawalNFT', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'WAD', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allowance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'asset', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'assetsToShares', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'decimals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'distributeRewards', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'exchangeRate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'governanceExecutor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initiateWithdraw', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lockedAssets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setGovernanceExecutor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setUnbondingPeriod', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'sharesToAssets', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'symbol', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalSupply', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unbondingPeriod', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawalNFT', data: BytesLike): Result;
  }

  
    export namespace ApprovalEvent {
      export type InputTuple = [owner: AddressLike, spender: AddressLike, value: BigNumberish];
      export type OutputTuple = [owner: string, spender: string, value: bigint];
      export interface OutputObject {owner: string, spender: string, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ClaimedEvent {
      export type InputTuple = [user: AddressLike, withdrawalId: BigNumberish, assetsPaid: BigNumberish];
      export type OutputTuple = [user: string, withdrawalId: bigint, assetsPaid: bigint];
      export interface OutputObject {user: string, withdrawalId: bigint, assetsPaid: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DepositedEvent {
      export type InputTuple = [user: AddressLike, assets: BigNumberish, shares: BigNumberish];
      export type OutputTuple = [user: string, assets: bigint, shares: bigint];
      export interface OutputObject {user: string, assets: bigint, shares: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DistributedRewardsEvent {
      export type InputTuple = [by: AddressLike, assets: BigNumberish];
      export type OutputTuple = [by: string, assets: bigint];
      export interface OutputObject {by: string, assets: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InitiatedWithdrawEvent {
      export type InputTuple = [user: AddressLike, sharesBurned: BigNumberish, assetsOwed: BigNumberish, withdrawalId: BigNumberish, availableAt: BigNumberish];
      export type OutputTuple = [user: string, sharesBurned: bigint, assetsOwed: bigint, withdrawalId: bigint, availableAt: bigint];
      export interface OutputObject {user: string, sharesBurned: bigint, assetsOwed: bigint, withdrawalId: bigint, availableAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferEvent {
      export type InputTuple = [from: AddressLike, to: AddressLike, value: BigNumberish];
      export type OutputTuple = [from: string, to: string, value: bigint];
      export interface OutputObject {from: string, to: string, value: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnbondingPeriodUpdatedEvent {
      export type InputTuple = [oldPeriod: BigNumberish, newPeriod: BigNumberish];
      export type OutputTuple = [oldPeriod: bigint, newPeriod: bigint];
      export interface OutputObject {oldPeriod: bigint, newPeriod: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface LiquidStakingVault extends BaseContract {
    
    connect(runner?: ContractRunner | null): LiquidStakingVault;
    waitForDeployment(): Promise<this>;

    interface: LiquidStakingVaultInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    WAD: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    allowance: TypedContractMethod<
      [owner: AddressLike, spender: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    approve: TypedContractMethod<
      [spender: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    asset: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    assetsToShares: TypedContractMethod<
      [assets: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    balanceOf: TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    claim: TypedContractMethod<
      [withdrawalId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    decimals: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    deposit: TypedContractMethod<
      [assets: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    distributeRewards: TypedContractMethod<
      [assets: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    exchangeRate: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    governanceExecutor: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    initiateWithdraw: TypedContractMethod<
      [shares: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    lockedAssets: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    name: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setGovernanceExecutor: TypedContractMethod<
      [_governanceExecutor: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setUnbondingPeriod: TypedContractMethod<
      [newPeriod: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    sharesToAssets: TypedContractMethod<
      [shares: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    symbol: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    totalSupply: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transfer: TypedContractMethod<
      [to: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    transferFrom: TypedContractMethod<
      [from: AddressLike, to: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    unbondingPeriod: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    withdrawalNFT: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'WAD'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'allowance'): TypedContractMethod<
      [owner: AddressLike, spender: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'approve'): TypedContractMethod<
      [spender: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'asset'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'assetsToShares'): TypedContractMethod<
      [assets: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'balanceOf'): TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'claim'): TypedContractMethod<
      [withdrawalId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'decimals'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'deposit'): TypedContractMethod<
      [assets: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'distributeRewards'): TypedContractMethod<
      [assets: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'exchangeRate'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'governanceExecutor'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'initiateWithdraw'): TypedContractMethod<
      [shares: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'lockedAssets'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'name'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setGovernanceExecutor'): TypedContractMethod<
      [_governanceExecutor: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setUnbondingPeriod'): TypedContractMethod<
      [newPeriod: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'sharesToAssets'): TypedContractMethod<
      [shares: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'symbol'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalSupply'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transfer'): TypedContractMethod<
      [to: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferFrom'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, value: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unbondingPeriod'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'withdrawalNFT'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'Approval'): TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
getEvent(key: 'Claimed'): TypedContractEvent<ClaimedEvent.InputTuple, ClaimedEvent.OutputTuple, ClaimedEvent.OutputObject>;
getEvent(key: 'Deposited'): TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
getEvent(key: 'DistributedRewards'): TypedContractEvent<DistributedRewardsEvent.InputTuple, DistributedRewardsEvent.OutputTuple, DistributedRewardsEvent.OutputObject>;
getEvent(key: 'InitiatedWithdraw'): TypedContractEvent<InitiatedWithdrawEvent.InputTuple, InitiatedWithdrawEvent.OutputTuple, InitiatedWithdrawEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'Transfer'): TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
getEvent(key: 'UnbondingPeriodUpdated'): TypedContractEvent<UnbondingPeriodUpdatedEvent.InputTuple, UnbondingPeriodUpdatedEvent.OutputTuple, UnbondingPeriodUpdatedEvent.OutputObject>;

    filters: {
      
      'Approval(address,address,uint256)': TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
      Approval: TypedContractEvent<ApprovalEvent.InputTuple, ApprovalEvent.OutputTuple, ApprovalEvent.OutputObject>;
    

      'Claimed(address,uint256,uint256)': TypedContractEvent<ClaimedEvent.InputTuple, ClaimedEvent.OutputTuple, ClaimedEvent.OutputObject>;
      Claimed: TypedContractEvent<ClaimedEvent.InputTuple, ClaimedEvent.OutputTuple, ClaimedEvent.OutputObject>;
    

      'Deposited(address,uint256,uint256)': TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
      Deposited: TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
    

      'DistributedRewards(address,uint256)': TypedContractEvent<DistributedRewardsEvent.InputTuple, DistributedRewardsEvent.OutputTuple, DistributedRewardsEvent.OutputObject>;
      DistributedRewards: TypedContractEvent<DistributedRewardsEvent.InputTuple, DistributedRewardsEvent.OutputTuple, DistributedRewardsEvent.OutputObject>;
    

      'InitiatedWithdraw(address,uint256,uint256,uint256,uint256)': TypedContractEvent<InitiatedWithdrawEvent.InputTuple, InitiatedWithdrawEvent.OutputTuple, InitiatedWithdrawEvent.OutputObject>;
      InitiatedWithdraw: TypedContractEvent<InitiatedWithdrawEvent.InputTuple, InitiatedWithdrawEvent.OutputTuple, InitiatedWithdrawEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'Transfer(address,address,uint256)': TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
      Transfer: TypedContractEvent<TransferEvent.InputTuple, TransferEvent.OutputTuple, TransferEvent.OutputObject>;
    

      'UnbondingPeriodUpdated(uint256,uint256)': TypedContractEvent<UnbondingPeriodUpdatedEvent.InputTuple, UnbondingPeriodUpdatedEvent.OutputTuple, UnbondingPeriodUpdatedEvent.OutputObject>;
      UnbondingPeriodUpdated: TypedContractEvent<UnbondingPeriodUpdatedEvent.InputTuple, UnbondingPeriodUpdatedEvent.OutputTuple, UnbondingPeriodUpdatedEvent.OutputObject>;
    
    };
  }